# Generated by Django 4.2.6 on 2023-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
