# Generated by Django 4.2.6 on 2023-11-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_product_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
